# Generated by Django 2.1 on 2019-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='年份')),
            ],
            options={
                'verbose_name': '年份管理',
                'verbose_name_plural': '年份管理',
            },
        ),
    ]
