# Generated by Django 2.1 on 2019-05-05 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.CharField(choices=[('1月', '1月'), ('2月', '2月'), ('3月', '3月'), ('4月', '4月'), ('5月', '5月'), ('6月', '6月'), ('7月', '7月'), ('8月', '8月'), ('9月', '9月'), ('10月', '10月'), ('11月', '11月'), ('12月', '12月')], default='1月', max_length=20, null=True, verbose_name='月份')),
                ('last_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='上月余额')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='工资收入')),
                ('other_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='其他收入')),
                ('payments', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支出')),
                ('expected_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预计余额')),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际余额')),
                ('balance_diff', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='余额误差')),
                ('actual_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实际存入')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('comments', models.CharField(max_length=200, verbose_name='备注')),
                ('Year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='piggy_bank.YearDB')),
            ],
            options={
                'verbose_name': '收入管理',
                'verbose_name_plural': '收入管理',
            },
        ),
    ]
