# Generated by Django 2.1 on 2019-05-06 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_bank', '0002_incomdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomdb',
            name='comments',
        ),
    ]
