# Generated by Django 2.1 on 2019-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_bank', '0003_remove_incomdb_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomdb',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='备注'),
        ),
    ]
