# Generated by Django 2.1 on 2019-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_bank', '0004_incomdb_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtee', models.CharField(max_length=20, verbose_name='债权人')),
                ('money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='借款')),
                ('all_money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总借款')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='还款')),
                ('all_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='已还')),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='剩余')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '债务管理',
                'verbose_name_plural': '债务管理',
            },
        ),
    ]
