# Generated by Django 2.1 on 2020-05-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piggy_bank', '0005_debtsdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPoolDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly', models.CharField(choices=[('1月', '1月'), ('2月', '2月'), ('3月', '3月'), ('4月', '4月'), ('5月', '5月'), ('6月', '6月'), ('7月', '7月'), ('8月', '8月'), ('9月', '9月'), ('10月', '10月'), ('11月', '11月'), ('12月', '12月')], default='1月', max_length=20, null=True, verbose_name='月份')),
                ('cash_pool', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='现金池')),
                ('insurance_pool', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='保险池')),
                ('goal_pool', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='目标池')),
                ('invest_pool', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金鹅池')),
                ('invest_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='投资回报')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='记录时间')),
                ('Year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='piggy_bank.YearDB')),
            ],
            options={
                'verbose_name': '资金池管理',
                'verbose_name_plural': '资金池管理',
            },
        ),
    ]
